function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 28-Jan-2020 15:15:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'ZDataSource','','MarkerFaceColor',[0 0 0],'MarkerSize',20,...
    'Marker','x',...
    'LineWidth',2,...
    'LineStyle','-.',...
    'Color',[1 0 1]);

box(axes1,'on');
